List<Map<String, String>> jsonData = [
  {'testName': '9급 국가직 공무원 건축계획', 'url': 'https://www.comcbt.com/xe/wc'},
  {'testName': '9급 국가직 공무원 건축구조', 'url': 'https://www.comcbt.com/xe/wd'},
  {'testName': '9급 국가직 공무원 경제학개론', 'url': 'https://www.comcbt.com/xe/we'},
  {'testName': '9급 국가직 공무원 공업화학', 'url': 'https://www.comcbt.com/xe/wf'},
  {'testName': '9급 국가직 공무원 공직선거법', 'url': 'https://www.comcbt.com/xe/wg'},
  {'testName': '9급 국가직 공무원 과학', 'url': 'https://www.comcbt.com/xe/wa'},
  {'testName': '9급 국가직 공무원 관세법개론', 'url': 'https://www.comcbt.com/xe/wh'},
  {'testName': '9급 국가직 공무원 교육학개론', 'url': 'https://www.comcbt.com/xe/wi'},
  {'testName': '9급 국가직 공무원 교정학개론', 'url': 'https://www.comcbt.com/xe/wj'},
  {'testName': '9급 국가직 공무원 국어', 'url': 'https://www.comcbt.com/xe/g3'},
  {'testName': '9급 국가직 공무원 국제법개론', 'url': 'https://www.comcbt.com/xe/wk'},
  {'testName': '9급 국가직 공무원 기계설계', 'url': 'https://www.comcbt.com/xe/wm'},
  {'testName': '9급 국가직 공무원 기계일반', 'url': 'https://www.comcbt.com/xe/wn'},
  {'testName': '9급 국가직 공무원 네트워크보안', 'url': 'https://www.comcbt.com/xe/wo'},
  {'testName': '9급 국가직 공무원 노동법개론', 'url': 'https://www.comcbt.com/xe/wp'},
  {'testName': '9급 국가직 공무원 무선공학개론', 'url': 'https://www.comcbt.com/xe/wq'},
  {'testName': '9급 국가직 공무원 사회', 'url': 'https://www.comcbt.com/xe/wb'},
  {'testName': '9급 국가직 공무원 사회복지학개론', 'url': 'https://www.comcbt.com/xe/wr'},
  {'testName': '9급 국가직 공무원 세법개론', 'url': 'https://www.comcbt.com/xe/ws'},
  {'testName': '9급 국가직 공무원 수학', 'url': 'https://www.comcbt.com/xe/w8'},
  {'testName': '9급 국가직 공무원 식용작물', 'url': 'https://www.comcbt.com/xe/wt'},
  {'testName': '9급 국가직 공무원 안전관리론', 'url': 'https://www.comcbt.com/xe/wu'},
  {'testName': '9급 국가직 공무원 영어', 'url': 'https://www.comcbt.com/xe/w9'},
  {'testName': '9급 국가직 공무원 응용역학개론', 'url': 'https://www.comcbt.com/xe/wv'},
  {'testName': '9급 국가직 공무원 임업경영', 'url': 'https://www.comcbt.com/xe/wx'},
  {'testName': '9급 국가직 공무원 재난관리론', 'url': 'https://www.comcbt.com/xe/wy'},
  {'testName': '9급 국가직 공무원 재배학개론', 'url': 'https://www.comcbt.com/xe/wz'},
  {'testName': '9급 국가직 공무원 전기기기', 'url': 'https://www.comcbt.com/xe/cn'},
  {'testName': '9급 국가직 공무원 전기이론', 'url': 'https://www.comcbt.com/xe/co'},
  {'testName': '9급 국가직 공무원 전자공학개론', 'url': 'https://www.comcbt.com/xe/cp'},
  {'testName': '9급 국가직 공무원 정보보호론', 'url': 'https://www.comcbt.com/xe/cr'},
  {'testName': '9급 국가직 공무원 정보시스템보안', 'url': 'https://www.comcbt.com/xe/cs'},
  {'testName': '9급 국가직 공무원 조경계획및설계', 'url': 'https://www.comcbt.com/xe/vs'},
  {'testName': '9급 국가직 공무원 조경학', 'url': 'https://www.comcbt.com/xe/vr'},
  {'testName': '9급 국가직 공무원 조림', 'url': 'https://www.comcbt.com/xe/ct'},
  {'testName': '9급 국가직 공무원 직업상담심리학개론', 'url': 'https://www.comcbt.com/xe/cu'},
  {'testName': '9급 국가직 공무원 컴퓨터일반', 'url': 'https://www.comcbt.com/xe/cv'},
  {'testName': '9급 국가직 공무원 토목설계', 'url': 'https://www.comcbt.com/xe/cw'},
  {'testName': '9급 국가직 공무원 통계학개론', 'url': 'https://www.comcbt.com/xe/cx'},
  {'testName': '9급 국가직 공무원 한국사', 'url': 'https://www.comcbt.com/xe/w7'},
  {'testName': '9급 국가직 공무원 행정법총론', 'url': 'https://www.comcbt.com/xe/cy'},
  {'testName': '9급 국가직 공무원 행정학개론', 'url': 'https://www.comcbt.com/xe/cz'},
  {'testName': '9급 국가직 공무원 형법', 'url': 'https://www.comcbt.com/xe/h5'},
  {'testName': '9급 국가직 공무원 형법총론', 'url': 'https://www.comcbt.com/xe/h6'},
  {'testName': '9급 국가직 공무원 형사소송법', 'url': 'https://www.comcbt.com/xe/h8'},
  {'testName': '9급 국가직 공무원 형사소송법개론', 'url': 'https://www.comcbt.com/xe/h7'},
  {'testName': '9급 국가직 공무원 화학공학일반', 'url': 'https://www.comcbt.com/xe/h9'},
  {'testName': '9급 국가직 공무원 회계원리', 'url': 'https://www.comcbt.com/xe/hb'},
  {'testName': '9급 국가직 공무원 회계학', 'url': 'https://www.comcbt.com/xe/hc'},
  {'testName': '9급 지방직 공무원 간호관리', 'url': 'https://www.comcbt.com/xe/qg'},
  {'testName': '9급 지방직 공무원 건축계획', 'url': 'https://www.comcbt.com/xe/qh'},
  {'testName': '9급 지방직 공무원 건축구조', 'url': 'https://www.comcbt.com/xe/qi'},
  {'testName': '9급 지방직 공무원 공업화학', 'url': 'https://www.comcbt.com/xe/qj'},
  {'testName': '9급 지방직 공무원 과학', 'url': 'https://www.comcbt.com/xe/qk'},
  {'testName': '9급 지방직 공무원 교육학개론', 'url': 'https://www.comcbt.com/xe/qm'},
  {'testName': '9급 지방직 공무원 국어', 'url': 'https://www.comcbt.com/xe/qn'},
  {'testName': '9급 지방직 공무원 기계설계', 'url': 'https://www.comcbt.com/xe/qo'},
  {'testName': '9급 지방직 공무원 기계일반', 'url': 'https://www.comcbt.com/xe/qp'},
  {'testName': '9급 지방직 공무원 사회', 'url': 'https://www.comcbt.com/xe/qq'},
  {'testName': '9급 지방직 공무원 사회복지학개론', 'url': 'https://www.comcbt.com/xe/qr'},
  {
    'testName': '9급 지방직 공무원 서울시 간호관리(8급)',
    'url': 'https://www.comcbt.com/xe/u1'
  },
  {'testName': '9급 지방직 공무원 서울시 건축계획', 'url': 'https://www.comcbt.com/xe/u2'},
  {'testName': '9급 지방직 공무원 서울시 건축구조', 'url': 'https://www.comcbt.com/xe/u3'},
  {'testName': '9급 지방직 공무원 서울시 공업화학', 'url': 'https://www.comcbt.com/xe/u4'},
  {'testName': '9급 지방직 공무원 서울시 공중보건', 'url': 'https://www.comcbt.com/xe/u5'},
  {'testName': '9급 지방직 공무원 서울시 과학', 'url': 'https://www.comcbt.com/xe/u6'},
  {'testName': '9급 지방직 공무원 서울시 국어', 'url': 'https://www.comcbt.com/xe/u7'},
  {'testName': '9급 지방직 공무원 서울시 기계설계', 'url': 'https://www.comcbt.com/xe/u8'},
  {'testName': '9급 지방직 공무원 서울시 기계일반', 'url': 'https://www.comcbt.com/xe/u9'},
  {'testName': '9급 지방직 공무원 서울시 물리', 'url': 'https://www.comcbt.com/xe/ua'},
  {'testName': '9급 지방직 공무원 서울시 보건행정', 'url': 'https://www.comcbt.com/xe/ub'},
  {'testName': '9급 지방직 공무원 서울시 사회', 'url': 'https://www.comcbt.com/xe/ud'},
  {'testName': '9급 지방직 공무원 서울시 사회(유공자)', 'url': 'https://www.comcbt.com/xe/uc'},
  {'testName': '9급 지방직 공무원 서울시 사회복지학개론', 'url': 'https://www.comcbt.com/xe/ue'},
  {'testName': '9급 지방직 공무원 서울시 생물', 'url': 'https://www.comcbt.com/xe/uf'},
  {'testName': '9급 지방직 공무원 서울시 선박일반', 'url': 'https://www.comcbt.com/xe/ug'},
  {'testName': '9급 지방직 공무원 서울시 수학', 'url': 'https://www.comcbt.com/xe/uh'},
  {'testName': '9급 지방직 공무원 서울시 수학(지적)', 'url': 'https://www.comcbt.com/xe/ui'},
  {'testName': '9급 지방직 공무원 서울시 식용작물', 'url': 'https://www.comcbt.com/xe/uj'},
  {'testName': '9급 지방직 공무원 서울시 안전관리론', 'url': 'https://www.comcbt.com/xe/uk'},
  {'testName': '9급 지방직 공무원 서울시 영어', 'url': 'https://www.comcbt.com/xe/um'},
  {'testName': '9급 지방직 공무원 서울시 응용역학개론', 'url': 'https://www.comcbt.com/xe/un'},
  {'testName': '9급 지방직 공무원 서울시 의료관계법규', 'url': 'https://www.comcbt.com/xe/uo'},
  {'testName': '9급 지방직 공무원 서울시 임업경영', 'url': 'https://www.comcbt.com/xe/up'},
  {'testName': '9급 지방직 공무원 서울시 자동차구조원리', 'url': 'https://www.comcbt.com/xe/uq'},
  {
    'testName': '9급 지방직 공무원 서울시 자동차구조원리(유공자)',
    'url': 'https://www.comcbt.com/xe/rq'
  },
  {'testName': '9급 지방직 공무원 서울시 자료조직개론', 'url': 'https://www.comcbt.com/xe/ur'},
  {'testName': '9급 지방직 공무원 서울시 재난관리론', 'url': 'https://www.comcbt.com/xe/us'},
  {'testName': '9급 지방직 공무원 서울시 재배학개론', 'url': 'https://www.comcbt.com/xe/ut'},
  {'testName': '9급 지방직 공무원 서울시 전기기기', 'url': 'https://www.comcbt.com/xe/uu'},
  {'testName': '9급 지방직 공무원 서울시 전기이론', 'url': 'https://www.comcbt.com/xe/uv'},
  {'testName': '9급 지방직 공무원 서울시 전자공학개론', 'url': 'https://www.comcbt.com/xe/uw'},
  {'testName': '9급 지방직 공무원 서울시 정보보호론', 'url': 'https://www.comcbt.com/xe/ux'},
  {'testName': '9급 지방직 공무원 서울시 정보봉사개론', 'url': 'https://www.comcbt.com/xe/uy'},
  {
    'testName': '9급 지방직 공무원 서울시 조경계획및생태관리',
    'url': 'https://www.comcbt.com/xe/uz'
  },
  {'testName': '9급 지방직 공무원 서울시 조경학', 'url': 'https://www.comcbt.com/xe/v1'},
  {'testName': '9급 지방직 공무원 서울시 조림', 'url': 'https://www.comcbt.com/xe/v2'},
  {'testName': '9급 지방직 공무원 서울시 지방세법', 'url': 'https://www.comcbt.com/xe/v3'},
  {'testName': '9급 지방직 공무원 서울시 지역사회간호', 'url': 'https://www.comcbt.com/xe/v4'},
  {'testName': '9급 지방직 공무원 서울시 지적법규', 'url': 'https://www.comcbt.com/xe/v5'},
  {'testName': '9급 지방직 공무원 서울시 지적측량', 'url': 'https://www.comcbt.com/xe/v6'},
  {'testName': '9급 지방직 공무원 서울시 컴퓨터일반', 'url': 'https://www.comcbt.com/xe/v7'},
  {'testName': '9급 지방직 공무원 서울시 토목설계', 'url': 'https://www.comcbt.com/xe/v8'},
  {'testName': '9급 지방직 공무원 서울시 통신이론', 'url': 'https://www.comcbt.com/xe/v9'},
  {'testName': '9급 지방직 공무원 서울시 한국사', 'url': 'https://www.comcbt.com/xe/vb'},
  {
    'testName': '9급 지방직 공무원 서울시 한국사(유공자)',
    'url': 'https://www.comcbt.com/xe/va'
  },
  {'testName': '9급 지방직 공무원 서울시 항해', 'url': 'https://www.comcbt.com/xe/vc'},
  {'testName': '9급 지방직 공무원 서울시 행정법총론', 'url': 'https://www.comcbt.com/xe/vd'},
  {'testName': '9급 지방직 공무원 서울시 행정학개론', 'url': 'https://www.comcbt.com/xe/ve'},
  {'testName': '9급 지방직 공무원 서울시 화학', 'url': 'https://www.comcbt.com/xe/vf'},
  {'testName': '9급 지방직 공무원 서울시 화학공학일반', 'url': 'https://www.comcbt.com/xe/vg'},
  {'testName': '9급 지방직 공무원 서울시 환경공학개론', 'url': 'https://www.comcbt.com/xe/vh'},
  {'testName': '9급 지방직 공무원 서울시 회계학', 'url': 'https://www.comcbt.com/xe/vi'},
  {'testName': '9급 지방직 공무원 수학', 'url': 'https://www.comcbt.com/xe/qs'},
  {'testName': '9급 지방직 공무원 식용작물', 'url': 'https://www.comcbt.com/xe/qt'},
  {'testName': '9급 지방직 공무원 안전관리론', 'url': 'https://www.comcbt.com/xe/qu'},
  {'testName': '9급 지방직 공무원 영어', 'url': 'https://www.comcbt.com/xe/qv'},
  {'testName': '9급 지방직 공무원 응용역학개론', 'url': 'https://www.comcbt.com/xe/qw'},
  {'testName': '9급 지방직 공무원 임업경영', 'url': 'https://www.comcbt.com/xe/qx'},
  {'testName': '9급 지방직 공무원 자료조직개론', 'url': 'https://www.comcbt.com/xe/qy'},
  {'testName': '9급 지방직 공무원 재난관리론', 'url': 'https://www.comcbt.com/xe/qz'},
  {'testName': '9급 지방직 공무원 재배학개론', 'url': 'https://www.comcbt.com/xe/r3'},
  {'testName': '9급 지방직 공무원 전기기기', 'url': 'https://www.comcbt.com/xe/r4'},
  {'testName': '9급 지방직 공무원 전기이론', 'url': 'https://www.comcbt.com/xe/r5'},
  {'testName': '9급 지방직 공무원 정보보호론', 'url': 'https://www.comcbt.com/xe/r6'},
  {'testName': '9급 지방직 공무원 정보봉사개론', 'url': 'https://www.comcbt.com/xe/r7'},
  {'testName': '9급 지방직 공무원 조림', 'url': 'https://www.comcbt.com/xe/r8'},
  {'testName': '9급 지방직 공무원 지방세법', 'url': 'https://www.comcbt.com/xe/r9'},
  {'testName': '9급 지방직 공무원 지역사회간호학', 'url': 'https://www.comcbt.com/xe/rb'},
  {'testName': '9급 지방직 공무원 지적전산학개론', 'url': 'https://www.comcbt.com/xe/rc'},
  {'testName': '9급 지방직 공무원 지적측량', 'url': 'https://www.comcbt.com/xe/rd'},
  {'testName': '9급 지방직 공무원 컴퓨터일반', 'url': 'https://www.comcbt.com/xe/re'},
  {'testName': '9급 지방직 공무원 토목설계', 'url': 'https://www.comcbt.com/xe/rf'},
  {'testName': '9급 지방직 공무원 한국사', 'url': 'https://www.comcbt.com/xe/rg'},
  {'testName': '9급 지방직 공무원 행정법총론', 'url': 'https://www.comcbt.com/xe/rh'},
  {'testName': '9급 지방직 공무원 행정학개론', 'url': 'https://www.comcbt.com/xe/ri'},
  {'testName': '9급 지방직 공무원 화학', 'url': 'https://www.comcbt.com/xe/rj'},
  {'testName': '9급 지방직 공무원 화학공학일반', 'url': 'https://www.comcbt.com/xe/rk'},
  {'testName': '9급 지방직 공무원 환경공학개론', 'url': 'https://www.comcbt.com/xe/rm'},
  {'testName': '9급 지방직 공무원 회계학', 'url': 'https://www.comcbt.com/xe/rn'},
  {'testName': 'DIAT 정보통신상식', 'url': 'https://www.comcbt.com/xe/d2'},
  {'testName': 'DIAT 정보통신상식(구)', 'url': 'https://www.comcbt.com/xe/d1'},
  {'testName': 'ERP 인사 2급 실무', 'url': 'https://www.comcbt.com/xe/ki'},
  {'testName': 'ERP 인사 2급 이론', 'url': 'https://www.comcbt.com/xe/kf'},
  {'testName': 'ERP 회계 2급 실무', 'url': 'https://www.comcbt.com/xe/kj'},
  {'testName': 'ERP 회계 2급 이론', 'url': 'https://www.comcbt.com/xe/kg'},
  {'testName': 'FAT 1급', 'url': 'https://www.comcbt.com/xe/kb'},
  {'testName': 'FAT 1급(구)', 'url': 'https://www.comcbt.com/xe/kc'},
  {'testName': 'FAT 2급', 'url': 'https://www.comcbt.com/xe/k9'},
  {'testName': 'FAT 2급(구)', 'url': 'https://www.comcbt.com/xe/ka'},
  {'testName': 'IoT지식능력검정', 'url': 'https://www.comcbt.com/xe/cco'},
  {'testName': 'PC정비사 1급', 'url': 'https://www.comcbt.com/xe/jd'},
  {'testName': 'PC정비사 2급', 'url': 'https://www.comcbt.com/xe/je'},
  {'testName': 'PSAT 상황판단', 'url': 'https://www.comcbt.com/xe/qc'},
  {'testName': 'PSAT 언어논리', 'url': 'https://www.comcbt.com/xe/qd'},
  {'testName': 'PSAT 자료해석', 'url': 'https://www.comcbt.com/xe/qe'},
  {'testName': 'PSAT 헌법', 'url': 'https://www.comcbt.com/xe/qf'},
  {'testName': 'RFID-GL', 'url': 'https://www.comcbt.com/xe/jv'},
  {'testName': 'TAT 1급', 'url': 'https://www.comcbt.com/xe/kd'},
  {'testName': 'TAT 2급', 'url': 'https://www.comcbt.com/xe/ke'},
  {'testName': 'TAT 2급(구)', 'url': 'https://www.comcbt.com/xe/kh'},
  {'testName': '가구제작기능사', 'url': 'https://www.comcbt.com/xe/mn'},
  {'testName': '가맹거래사', 'url': 'https://www.comcbt.com/xe/rp'},
  {'testName': '가스기능사', 'url': 'https://www.comcbt.com/xe/ks'},
  {'testName': '가스기능장', 'url': 'https://www.comcbt.com/xe/fs'},
  {'testName': '가스기사', 'url': 'https://www.comcbt.com/xe/df'},
  {'testName': '가스산업기사', 'url': 'https://www.comcbt.com/xe/no'},
  {'testName': '감정평가사 1차 1교시', 'url': 'https://www.comcbt.com/xe/cek'},
  {'testName': '감정평가사 1차 1교시(구)', 'url': 'https://www.comcbt.com/xe/cen'},
  {'testName': '감정평가사 1차 2교시', 'url': 'https://www.comcbt.com/xe/cem'},
  {'testName': '건설기계설비기사', 'url': 'https://www.comcbt.com/xe/e7'},
  {'testName': '건설기계설비산업기사', 'url': 'https://www.comcbt.com/xe/mx'},
  {'testName': '건설기계정비기능사', 'url': 'https://www.comcbt.com/xe/e6'},
  {'testName': '건설기계정비기능장', 'url': 'https://www.comcbt.com/xe/can'},
  {'testName': '건설기계정비산업기사', 'url': 'https://www.comcbt.com/xe/gw'},
  {'testName': '건설안전기사', 'url': 'https://www.comcbt.com/xe/nj'},
  {'testName': '건설안전산업기사', 'url': 'https://www.comcbt.com/xe/bj'},
  {'testName': '건설재료시험기능사', 'url': 'https://www.comcbt.com/xe/ee'},
  {'testName': '건설재료시험기사', 'url': 'https://www.comcbt.com/xe/do'},
  {'testName': '건설재료시험산업기사', 'url': 'https://www.comcbt.com/xe/ge'},
  {'testName': '건축기사', 'url': 'https://www.comcbt.com/xe/nf'},
  {'testName': '건축목공산업기사', 'url': 'https://www.comcbt.com/xe/ccm'},
  {'testName': '건축목재시공기능장', 'url': 'https://www.comcbt.com/xe/cat'},
  {'testName': '건축산업기사', 'url': 'https://www.comcbt.com/xe/bt'},
  {'testName': '건축설비기사', 'url': 'https://www.comcbt.com/xe/du'},
  {'testName': '건축설비산업기사', 'url': 'https://www.comcbt.com/xe/fe'},
  {'testName': '건축일반시공기능장', 'url': 'https://www.comcbt.com/xe/cap'},
  {'testName': '건축일반시공산업기사', 'url': 'https://www.comcbt.com/xe/cci'},
  {'testName': '경비지도사 1차(법학개론,민간경비론)', 'url': 'https://www.comcbt.com/xe/pd'},
  {'testName': '경비지도사 2차(경비업법)', 'url': 'https://www.comcbt.com/xe/pe'},
  {'testName': '경비지도사 2차(경호학)', 'url': 'https://www.comcbt.com/xe/ph'},
  {'testName': '경비지도사 2차(기계경비개론)', 'url': 'https://www.comcbt.com/xe/pf'},
  {'testName': '경비지도사 2차(기계경비기획및설계)', 'url': 'https://www.comcbt.com/xe/pg'},
  {'testName': '경비지도사 2차(범죄학)', 'url': 'https://www.comcbt.com/xe/pi'},
  {'testName': '경비지도사 2차(소방학)', 'url': 'https://www.comcbt.com/xe/pj'},
  {'testName': '경영지도사 1차', 'url': 'https://www.comcbt.com/xe/cfm'},
  {'testName': '경영지도사 1차 1교시', 'url': 'https://www.comcbt.com/xe/cda'},
  {'testName': '경영지도사 1차 1교시(구)', 'url': 'https://www.comcbt.com/xe/rt'},
  {'testName': '경영지도사 1차 2교시', 'url': 'https://www.comcbt.com/xe/cdb'},
  {'testName': '경영지도사 1차 2교시(구)', 'url': 'https://www.comcbt.com/xe/ru'},
  {'testName': '경찰공무원(순경) 경찰학개론', 'url': 'https://www.comcbt.com/xe/p5'},
  {'testName': '경찰공무원(순경) 과학', 'url': 'https://www.comcbt.com/xe/p9'},
  {'testName': '경찰공무원(순경) 국어', 'url': 'https://www.comcbt.com/xe/p6'},
  {'testName': '경찰공무원(순경) 사회', 'url': 'https://www.comcbt.com/xe/p8'},
  {'testName': '경찰공무원(순경) 수사', 'url': 'https://www.comcbt.com/xe/pa'},
  {'testName': '경찰공무원(순경) 수학', 'url': 'https://www.comcbt.com/xe/p7'},
  {'testName': '경찰공무원(순경) 영어', 'url': 'https://www.comcbt.com/xe/p2'},
  {'testName': '경찰공무원(순경) 한국사', 'url': 'https://www.comcbt.com/xe/p1'},
  {'testName': '경찰공무원(순경) 행정법', 'url': 'https://www.comcbt.com/xe/pb'},
  {'testName': '경찰공무원(순경) 형법', 'url': 'https://www.comcbt.com/xe/p3'},
  {'testName': '경찰공무원(순경) 형사소송법', 'url': 'https://www.comcbt.com/xe/p4'},
  {'testName': '계리직 공무원 금융상식', 'url': 'https://www.comcbt.com/xe/cff'},
  {'testName': '계리직 공무원 우편', 'url': 'https://www.comcbt.com/xe/cfe'},
  {'testName': '계리직공무원 우편 및 금융상식', 'url': 'https://www.comcbt.com/xe/mk'},
  {'testName': '계리직공무원 컴퓨터 일반', 'url': 'https://www.comcbt.com/xe/mm'},
  {'testName': '계리직공무원 한국사', 'url': 'https://www.comcbt.com/xe/mj'},
  {'testName': '공유압기능사', 'url': 'https://www.comcbt.com/xe/b6'},
  {'testName': '공인노무사 1차(경영학개론)', 'url': 'https://www.comcbt.com/xe/cfs'},
  {'testName': '공인노무사 1차(경제학원론)', 'url': 'https://www.comcbt.com/xe/cfr'},
  {'testName': '공인노무사 1차(노동법1)', 'url': 'https://www.comcbt.com/xe/cfn'},
  {'testName': '공인노무사 1차(노동법2)', 'url': 'https://www.comcbt.com/xe/cfo'},
  {'testName': '공인노무사 1차(민법)', 'url': 'https://www.comcbt.com/xe/cfp'},
  {'testName': '공인노무사 1차(사회보험법)', 'url': 'https://www.comcbt.com/xe/cfq'},
  {'testName': '공인중개사 1차', 'url': 'https://www.comcbt.com/xe/g1'},
  {'testName': '공인중개사 2차', 'url': 'https://www.comcbt.com/xe/g2'},
  {'testName': '공조냉동기계기능사', 'url': 'https://www.comcbt.com/xe/n5'},
  {'testName': '공조냉동기계기사', 'url': 'https://www.comcbt.com/xe/cer'},
  {'testName': '공조냉동기계기사(구)', 'url': 'https://www.comcbt.com/xe/bz'},
  {'testName': '공조냉동기계산업기사', 'url': 'https://www.comcbt.com/xe/nq'},
  {'testName': '관광통역안내사 1교시', 'url': 'https://www.comcbt.com/xe/cg'},
  {'testName': '관광통역안내사 2교시', 'url': 'https://www.comcbt.com/xe/ci'},
  {'testName': '광고도장기능사', 'url': 'https://www.comcbt.com/xe/cdo'},
  {'testName': '광학기능사', 'url': 'https://www.comcbt.com/xe/cec'},
  {'testName': '광학기사', 'url': 'https://www.comcbt.com/xe/caf'},
  {'testName': '교통기사', 'url': 'https://www.comcbt.com/xe/ff'},
  {'testName': '교통산업기사', 'url': 'https://www.comcbt.com/xe/cde'},
  {'testName': '국내여행안내사 1차', 'url': 'https://www.comcbt.com/xe/cf'},
  {'testName': '굴삭기운전기능사', 'url': 'https://www.comcbt.com/xe/jh'},
  {'testName': '귀금속가공기능사', 'url': 'https://www.comcbt.com/xe/hq'},
  {'testName': '귀금속가공기능장', 'url': 'https://www.comcbt.com/xe/cau'},
  {'testName': '귀금속가공산업기사', 'url': 'https://www.comcbt.com/xe/cav'},
  {'testName': '금속도장기능사', 'url': 'https://www.comcbt.com/xe/hp'},
  {'testName': '금속재료기능장', 'url': 'https://www.comcbt.com/xe/vk'},
  {'testName': '금속재료기사', 'url': 'https://www.comcbt.com/xe/hn'},
  {'testName': '금속재료산업기사', 'url': 'https://www.comcbt.com/xe/ds'},
  {'testName': '금속재료시험기능사', 'url': 'https://www.comcbt.com/xe/c6'},
  {'testName': '금형기능사', 'url': 'https://www.comcbt.com/xe/gt'},
  {'testName': '금형제작기능장', 'url': 'https://www.comcbt.com/xe/caq'},
  {'testName': '기계가공기능장', 'url': 'https://www.comcbt.com/xe/rz'},
  {'testName': '기계가공조립기능사', 'url': 'https://www.comcbt.com/xe/da'},
  {'testName': '기계설계기사', 'url': 'https://www.comcbt.com/xe/mz'},
  {'testName': '기계설계산업기사', 'url': 'https://www.comcbt.com/xe/be'},
  {'testName': '기계정비기능사', 'url': 'https://www.comcbt.com/xe/mv'},
  {'testName': '기계정비산업기사', 'url': 'https://www.comcbt.com/xe/bd'},
  {'testName': '기계조립산업기사', 'url': 'https://www.comcbt.com/xe/gx'},
  {'testName': '기상기사', 'url': 'https://www.comcbt.com/xe/c5'},
  {'testName': '네트워크관리사 1급', 'url': 'https://www.comcbt.com/xe/jn'},
  {'testName': '네트워크관리사 2급', 'url': 'https://www.comcbt.com/xe/jf'},
  {'testName': '농기계운전기능사', 'url': 'https://www.comcbt.com/xe/g4'},
  {'testName': '농기계정비기능사', 'url': 'https://www.comcbt.com/xe/fa'},
  {'testName': '농림토양평가관리산업기사', 'url': 'https://www.comcbt.com/xe/cdy'},
  {'testName': '농산물품질관리사 1차', 'url': 'https://www.comcbt.com/xe/ccv'},
  {'testName': '농업기계기사', 'url': 'https://www.comcbt.com/xe/cdt'},
  {'testName': '농업기계산업기사', 'url': 'https://www.comcbt.com/xe/mr'},
  {'testName': '농작업안전보건기사', 'url': 'https://www.comcbt.com/xe/px'},
  {'testName': '누설비파괴검사기사', 'url': 'https://www.comcbt.com/xe/pz'},
  {'testName': '누설비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/py'},
  {'testName': '대기환경기사', 'url': 'https://www.comcbt.com/xe/b4'},
  {'testName': '대기환경산업기사', 'url': 'https://www.comcbt.com/xe/ez'},
  {'testName': '도시계획기사', 'url': 'https://www.comcbt.com/xe/dy'},
  {'testName': '도자기공예기능사', 'url': 'https://www.comcbt.com/xe/m6'},
  {'testName': '동력기계정비기능사', 'url': 'https://www.comcbt.com/xe/ced'},
  {'testName': '디지털영상편집 1급', 'url': 'https://www.comcbt.com/xe/hg'},
  {'testName': '디지털영상편집 2급', 'url': 'https://www.comcbt.com/xe/hf'},
  {'testName': '리눅스마스터 1급', 'url': 'https://www.comcbt.com/xe/r1'},
  {'testName': '리눅스마스터 2급', 'url': 'https://www.comcbt.com/xe/r2'},
  {'testName': '멀티미디어콘텐츠제작전문가', 'url': 'https://www.comcbt.com/xe/d4'},
  {'testName': '멀티미디어콘텐츠제작전문가(구)', 'url': 'https://www.comcbt.com/xe/d3'},
  {'testName': '모터그레이더운전기능사', 'url': 'https://www.comcbt.com/xe/ceg'},
  {'testName': '목공예기능사', 'url': 'https://www.comcbt.com/xe/ccu'},
  {'testName': '무선설비기능사', 'url': 'https://www.comcbt.com/xe/ceh'},
  {'testName': '무선설비기사', 'url': 'https://www.comcbt.com/xe/b8'},
  {'testName': '무선설비산업기사', 'url': 'https://www.comcbt.com/xe/bb'},
  {'testName': '물류관리사 1교시', 'url': 'https://www.comcbt.com/xe/hh'},
  {'testName': '물류관리사 2교시', 'url': 'https://www.comcbt.com/xe/hi'},
  {'testName': '미용사(네일)', 'url': 'https://www.comcbt.com/xe/k4'},
  {'testName': '미용사(일반)', 'url': 'https://www.comcbt.com/xe/jc'},
  {'testName': '미용사(피부)', 'url': 'https://www.comcbt.com/xe/jm'},
  {'testName': '미용장', 'url': 'https://www.comcbt.com/xe/cag'},
  {'testName': '바리스타 2급', 'url': 'https://www.comcbt.com/xe/b2'},
  {'testName': '바이오화학제품제조기사', 'url': 'https://www.comcbt.com/xe/ro'},
  {'testName': '반도체설계산업기사', 'url': 'https://www.comcbt.com/xe/cca'},
  {'testName': '방사선비파괴검사기능사', 'url': 'https://www.comcbt.com/xe/en'},
  {'testName': '방사선비파괴검사기사', 'url': 'https://www.comcbt.com/xe/fm'},
  {'testName': '방사선비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/fn'},
  {'testName': '방사선비파괴검사산업기사', 'url': 'https://www.comcbt.com/xe/me'},
  {'testName': '방사선비파괴검사산업기사(구)', 'url': 'https://www.comcbt.com/xe/mf'},
  {'testName': '방송통신기능사', 'url': 'https://www.comcbt.com/xe/cei'},
  {'testName': '방송통신기사', 'url': 'https://www.comcbt.com/xe/cfg'},
  {'testName': '방송통신기사(구)', 'url': 'https://www.comcbt.com/xe/kz'},
  {'testName': '방송통신산업기사', 'url': 'https://www.comcbt.com/xe/cfj'},
  {'testName': '방송통신산업기사(구)', 'url': 'https://www.comcbt.com/xe/bn'},
  {'testName': '방수산업기사', 'url': 'https://www.comcbt.com/xe/vn'},
  {'testName': '방재기사', 'url': 'https://www.comcbt.com/xe/cfb'},
  {'testName': '배관기능사', 'url': 'https://www.comcbt.com/xe/gc'},
  {'testName': '배관기능장', 'url': 'https://www.comcbt.com/xe/g7'},
  {'testName': '버섯종균기능사', 'url': 'https://www.comcbt.com/xe/di'},
  {'testName': '법조윤리', 'url': 'https://www.comcbt.com/xe/cfa'},
  {'testName': '변리사 1차(1교시)', 'url': 'https://www.comcbt.com/xe/hj'},
  {'testName': '변리사 1차(2교시)', 'url': 'https://www.comcbt.com/xe/hk'},
  {'testName': '변리사 1차(3교시)', 'url': 'https://www.comcbt.com/xe/hm'},
  {'testName': '보석가공기능사', 'url': 'https://www.comcbt.com/xe/cdz'},
  {'testName': '보석감정사(기능사)', 'url': 'https://www.comcbt.com/xe/gf'},
  {'testName': '비서 1급', 'url': 'https://www.comcbt.com/xe/w4'},
  {'testName': '비서 2급', 'url': 'https://www.comcbt.com/xe/w5'},
  {'testName': '비서 3급', 'url': 'https://www.comcbt.com/xe/w6'},
  {'testName': '사무자동화산업기사', 'url': 'https://www.comcbt.com/xe/j6'},
  {'testName': '사진기능사', 'url': 'https://www.comcbt.com/xe/kk'},
  {'testName': '사출(프레스)금형산업기사', 'url': 'https://www.comcbt.com/xe/g5'},
  {'testName': '사출(프레스)금형설계기사', 'url': 'https://www.comcbt.com/xe/gs'},
  {'testName': '사회복지사 1급(1교시)', 'url': 'https://www.comcbt.com/xe/f1'},
  {'testName': '사회복지사 1급(1교시)(구)', 'url': 'https://www.comcbt.com/xe/f4'},
  {'testName': '사회복지사 1급(2교시)', 'url': 'https://www.comcbt.com/xe/f2'},
  {'testName': '사회복지사 1급(2교시)(구)', 'url': 'https://www.comcbt.com/xe/f5'},
  {'testName': '사회복지사 1급(3교시)', 'url': 'https://www.comcbt.com/xe/f3'},
  {'testName': '사회복지사 1급(3교시)(구)', 'url': 'https://www.comcbt.com/xe/f6'},
  {'testName': '사회조사분석사 1급', 'url': 'https://www.comcbt.com/xe/he'},
  {'testName': '사회조사분석사 2급', 'url': 'https://www.comcbt.com/xe/s2'},
  {'testName': '산림기능사', 'url': 'https://www.comcbt.com/xe/nz'},
  {'testName': '산림기사', 'url': 'https://www.comcbt.com/xe/b5'},
  {'testName': '산림산업기사', 'url': 'https://www.comcbt.com/xe/bc'},
  {'testName': '산림산업기사(구60문항)', 'url': 'https://www.comcbt.com/xe/bh'},
  {'testName': '산업보건지도사', 'url': 'https://www.comcbt.com/xe/vw'},
  {'testName': '산업안전기사', 'url': 'https://www.comcbt.com/xe/ku'},
  {'testName': '산업안전산업기사', 'url': 'https://www.comcbt.com/xe/kv'},
  {'testName': '산업안전지도사', 'url': 'https://www.comcbt.com/xe/caa'},
  {'testName': '산업위생관리기사', 'url': 'https://www.comcbt.com/xe/bw'},
  {'testName': '산업위생관리산업기사', 'url': 'https://www.comcbt.com/xe/dz'},
  {'testName': '생물분류기사(동물)', 'url': 'https://www.comcbt.com/xe/qa'},
  {'testName': '생물분류기사(식물)', 'url': 'https://www.comcbt.com/xe/qb'},
  {'testName': '생산자동화기능사', 'url': 'https://www.comcbt.com/xe/n8'},
  {'testName': '생산자동화산업기사', 'url': 'https://www.comcbt.com/xe/e8'},
  {'testName': '석공예기능사', 'url': 'https://www.comcbt.com/xe/cef'},
  {'testName': '선체건조기능사', 'url': 'https://www.comcbt.com/xe/cce'},
  {'testName': '설비보전기능사', 'url': 'https://www.comcbt.com/xe/nm'},
  {'testName': '설비보전기사', 'url': 'https://www.comcbt.com/xe/cet'},
  {'testName': '설비보전기사(구)', 'url': 'https://www.comcbt.com/xe/de'},
  {'testName': '섬유디자인산업기사', 'url': 'https://www.comcbt.com/xe/cdm'},
  {'testName': '세탁기능사', 'url': 'https://www.comcbt.com/xe/kn'},
  {'testName': '소방공무원(경력) 생활영어', 'url': 'https://www.comcbt.com/xe/pv'},
  {'testName': '소방공무원(경력) 소방관계법규', 'url': 'https://www.comcbt.com/xe/pw'},
  {'testName': '소방공무원(공개) 과학', 'url': 'https://www.comcbt.com/xe/pt'},
  {'testName': '소방공무원(공개) 사회', 'url': 'https://www.comcbt.com/xe/ps'},
  {'testName': '소방공무원(공개) 소방관계법규', 'url': 'https://www.comcbt.com/xe/pr'},
  {'testName': '소방공무원(공개) 수학', 'url': 'https://www.comcbt.com/xe/pu'},
  {'testName': '소방공무원(공개) 한국사', 'url': 'https://www.comcbt.com/xe/pm'},
  {'testName': '소방공무원(공개) 행정법총론', 'url': 'https://www.comcbt.com/xe/pq'},
  {'testName': '소방공무원(공개,경력) 국어', 'url': 'https://www.comcbt.com/xe/pk'},
  {'testName': '소방공무원(공개,경력) 소방학개론', 'url': 'https://www.comcbt.com/xe/po'},
  {'testName': '소방공무원(공개,경력) 영어', 'url': 'https://www.comcbt.com/xe/pn'},
  {'testName': '소방설비기사(기계분야)', 'url': 'https://www.comcbt.com/xe/nd'},
  {'testName': '소방설비기사(전기분야)', 'url': 'https://www.comcbt.com/xe/nc'},
  {'testName': '소방설비산업기사(기계)', 'url': 'https://www.comcbt.com/xe/nw'},
  {'testName': '소방설비산업기사(전기)', 'url': 'https://www.comcbt.com/xe/nv'},
  {'testName': '소방시설관리사', 'url': 'https://www.comcbt.com/xe/ft'},
  {'testName': '소비자전문상담사 2급', 'url': 'https://www.comcbt.com/xe/gb'},
  {'testName': '소음진동기사', 'url': 'https://www.comcbt.com/xe/cez'},
  {'testName': '소음진동기사(구)', 'url': 'https://www.comcbt.com/xe/gq'},
  {'testName': '소음진동산업기사', 'url': 'https://www.comcbt.com/xe/gr'},
  {'testName': '손해평가사', 'url': 'https://www.comcbt.com/xe/ce'},
  {'testName': '수능(경제)', 'url': 'https://www.comcbt.com/xe/sd'},
  {'testName': '수능(국사)', 'url': 'https://www.comcbt.com/xe/s4'},
  {'testName': '수능(국어영역)', 'url': 'https://www.comcbt.com/xe/so'},
  {'testName': '수능(동아시아사)', 'url': 'https://www.comcbt.com/xe/sa'},
  {'testName': '수능(물리I)', 'url': 'https://www.comcbt.com/xe/se'},
  {'testName': '수능(물리II)', 'url': 'https://www.comcbt.com/xe/sg'},
  {'testName': '수능(법과정치)', 'url': 'https://www.comcbt.com/xe/sc'},
  {'testName': '수능(생명과학I)', 'url': 'https://www.comcbt.com/xe/sj'},
  {'testName': '수능(생명과학II)', 'url': 'https://www.comcbt.com/xe/sk'},
  {'testName': '수능(생활과윤리)', 'url': 'https://www.comcbt.com/xe/s6'},
  {'testName': '수능(세계사)', 'url': 'https://www.comcbt.com/xe/sb'},
  {'testName': '수능(세계지리)', 'url': 'https://www.comcbt.com/xe/s9'},
  {'testName': '수능(윤리와사상)', 'url': 'https://www.comcbt.com/xe/s7'},
  {'testName': '수능(지구과학I)', 'url': 'https://www.comcbt.com/xe/sm'},
  {'testName': '수능(지구과학II)', 'url': 'https://www.comcbt.com/xe/sn'},
  {'testName': '수능(한국근ㆍ현대사)', 'url': 'https://www.comcbt.com/xe/s5'},
  {'testName': '수능(한국사)', 'url': 'https://www.comcbt.com/xe/s3'},
  {'testName': '수능(한국지리)', 'url': 'https://www.comcbt.com/xe/s8'},
  {'testName': '수능(화학I)', 'url': 'https://www.comcbt.com/xe/sh'},
  {'testName': '수능(화학II)', 'url': 'https://www.comcbt.com/xe/si'},
  {'testName': '수산물품질관리사 1차', 'url': 'https://www.comcbt.com/xe/cee'},
  {'testName': '수산양식기능사', 'url': 'https://www.comcbt.com/xe/cae'},
  {'testName': '수산양식기사', 'url': 'https://www.comcbt.com/xe/fr'},
  {'testName': '수산양식산업기사', 'url': 'https://www.comcbt.com/xe/ra'},
  {'testName': '수산제조기사', 'url': 'https://www.comcbt.com/xe/cdg'},
  {'testName': '수질환경기사', 'url': 'https://www.comcbt.com/xe/nk'},
  {'testName': '수질환경산업기사', 'url': 'https://www.comcbt.com/xe/dg'},
  {'testName': '스포츠경영관리사', 'url': 'https://www.comcbt.com/xe/fz'},
  {'testName': '승강기기능사', 'url': 'https://www.comcbt.com/xe/k5'},
  {'testName': '승강기기사', 'url': 'https://www.comcbt.com/xe/bg'},
  {'testName': '승강기산업기사', 'url': 'https://www.comcbt.com/xe/gh'},
  {'testName': '시각디자인기사', 'url': 'https://www.comcbt.com/xe/q2'},
  {'testName': '시각디자인산업기사', 'url': 'https://www.comcbt.com/xe/fb'},
  {'testName': '시설원예기사', 'url': 'https://www.comcbt.com/xe/ccr'},
  {'testName': '식물보호기사', 'url': 'https://www.comcbt.com/xe/bv'},
  {'testName': '식물보호산업기사', 'url': 'https://www.comcbt.com/xe/eq'},
  {'testName': '식육가공기사', 'url': 'https://www.comcbt.com/xe/cej'},
  {'testName': '식품가공기능사', 'url': 'https://www.comcbt.com/xe/fp'},
  {'testName': '식품기사', 'url': 'https://www.comcbt.com/xe/ne'},
  {'testName': '식품산업기사', 'url': 'https://www.comcbt.com/xe/et'},
  {'testName': '식품산업기사(구)', 'url': 'https://www.comcbt.com/xe/dq'},
  {'testName': '신발류제조기능사', 'url': 'https://www.comcbt.com/xe/cds'},
  {'testName': '신재생에너지발전설비기능사', 'url': 'https://www.comcbt.com/xe/n9'},
  {'testName': '신재생에너지발전설비기사', 'url': 'https://www.comcbt.com/xe/rr'},
  {'testName': '신재생에너지발전설비기사(구)', 'url': 'https://www.comcbt.com/xe/dt'},
  {'testName': '신재생에너지발전설비산업기사', 'url': 'https://www.comcbt.com/xe/fi'},
  {'testName': '실내건축기능사', 'url': 'https://www.comcbt.com/xe/d6'},
  {'testName': '실내건축기사', 'url': 'https://www.comcbt.com/xe/cew'},
  {'testName': '실내건축기사(구)', 'url': 'https://www.comcbt.com/xe/dc'},
  {'testName': '실내건축산업기사', 'url': 'https://www.comcbt.com/xe/dp'},
  {'testName': '압연기능사', 'url': 'https://www.comcbt.com/xe/ey'},
  {'testName': '압연기능장', 'url': 'https://www.comcbt.com/xe/caj'},
  {'testName': '양복기능사', 'url': 'https://www.comcbt.com/xe/rw'},
  {'testName': '양장기능사', 'url': 'https://www.comcbt.com/xe/ec'},
  {'testName': '양화장치운전기능사', 'url': 'https://www.comcbt.com/xe/q7'},
  {'testName': '어로산업기사', 'url': 'https://www.comcbt.com/xe/md'},
  {'testName': '에너지관리기능사', 'url': 'https://www.comcbt.com/xe/kp'},
  {'testName': '에너지관리기능장', 'url': 'https://www.comcbt.com/xe/rx'},
  {'testName': '에너지관리기사', 'url': 'https://www.comcbt.com/xe/dd'},
  {'testName': '에너지관리산업기사', 'url': 'https://www.comcbt.com/xe/em'},
  {'testName': '연구실안전관리사', 'url': 'https://www.comcbt.com/xe/cfc'},
  {'testName': '연삭기능사', 'url': 'https://www.comcbt.com/xe/cdc'},
  {'testName': '열처리기능사', 'url': 'https://www.comcbt.com/xe/f7'},
  {'testName': '염색기능사', 'url': 'https://www.comcbt.com/xe/cea'},
  {'testName': '영사기능사', 'url': 'https://www.comcbt.com/xe/rv'},
  {'testName': '온실가스관리기사', 'url': 'https://www.comcbt.com/xe/fd'},
  {'testName': '와전류비파괴검사기사', 'url': 'https://www.comcbt.com/xe/q5'},
  {'testName': '와전류비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/q9'},
  {'testName': '용접기능사', 'url': 'https://www.comcbt.com/xe/jr'},
  {'testName': '용접기능장', 'url': 'https://www.comcbt.com/xe/gp'},
  {'testName': '용접기사', 'url': 'https://www.comcbt.com/xe/np'},
  {'testName': '용접산업기사', 'url': 'https://www.comcbt.com/xe/bx'},
  {
    'testName': '운전면허 학과시험(필기) 1종 2종(2020년판',
    'url': 'https://www.comcbt.com/xe/vp'
  },
  {'testName': '운전면허 학과시험(필기) 2종 소형 이륜', 'url': 'https://www.comcbt.com/xe/vq'},
  {'testName': '워드프로세서 (구 1급)', 'url': 'https://www.comcbt.com/xe/w1'},
  {'testName': '워드프로세서 2급(폐지)', 'url': 'https://www.comcbt.com/xe/w2'},
  {'testName': '워드프로세서 3급(폐지)', 'url': 'https://www.comcbt.com/xe/w3'},
  {'testName': '원예기능사', 'url': 'https://www.comcbt.com/xe/m7'},
  {'testName': '원자력기사', 'url': 'https://www.comcbt.com/xe/ccj'},
  {'testName': '원형기능사', 'url': 'https://www.comcbt.com/xe/cdw'},
  {'testName': '웹디자인기능사', 'url': 'https://www.comcbt.com/xe/j9'},
  {'testName': '위험물기능사', 'url': 'https://www.comcbt.com/xe/jy'},
  {'testName': '위험물기능장', 'url': 'https://www.comcbt.com/xe/g6'},
  {'testName': '위험물산업기사', 'url': 'https://www.comcbt.com/xe/ng'},
  {'testName': '유기농업기능사', 'url': 'https://www.comcbt.com/xe/d9'},
  {'testName': '유기농업기사', 'url': 'https://www.comcbt.com/xe/eb'},
  {'testName': '유기농업산업기사', 'url': 'https://www.comcbt.com/xe/q6'},
  {'testName': '유통관리사 1급', 'url': 'https://www.comcbt.com/xe/vt'},
  {'testName': '유통관리사 2급', 'url': 'https://www.comcbt.com/xe/vu'},
  {'testName': '유통관리사 3급', 'url': 'https://www.comcbt.com/xe/vv'},
  {'testName': '육상무선통신사', 'url': 'https://www.comcbt.com/xe/cfk'},
  {'testName': '응용지질기사', 'url': 'https://www.comcbt.com/xe/ck'},
  {'testName': '의공기사', 'url': 'https://www.comcbt.com/xe/fo'},
  {'testName': '의공산업기사', 'url': 'https://www.comcbt.com/xe/m9'},
  {'testName': '의료전자기능사', 'url': 'https://www.comcbt.com/xe/cj'},
  {'testName': '의류기사', 'url': 'https://www.comcbt.com/xe/ccf'},
  {'testName': '이용사', 'url': 'https://www.comcbt.com/xe/by'},
  {'testName': '이용장', 'url': 'https://www.comcbt.com/xe/cak'},
  {'testName': '인간공학기사', 'url': 'https://www.comcbt.com/xe/c9'},
  {'testName': '인쇄기능사', 'url': 'https://www.comcbt.com/xe/mw'},
  {'testName': '인쇄기사', 'url': 'https://www.comcbt.com/xe/ccp'},
  {'testName': '인쇄산업기사', 'url': 'https://www.comcbt.com/xe/ccs'},
  {'testName': '인터넷보안전문가 2급', 'url': 'https://www.comcbt.com/xe/i2'},
  {'testName': '인터넷정보관리사 2급', 'url': 'https://www.comcbt.com/xe/k7'},
  {'testName': '일반기계기사', 'url': 'https://www.comcbt.com/xe/ny'},
  {'testName': '임산가공기능사', 'url': 'https://www.comcbt.com/xe/ma'},
  {'testName': '임산가공기사', 'url': 'https://www.comcbt.com/xe/q4'},
  {'testName': '임산가공산업기사', 'url': 'https://www.comcbt.com/xe/cdu'},
  {'testName': '임상심리사 1급', 'url': 'https://www.comcbt.com/xe/mo'},
  {'testName': '임상심리사 2급', 'url': 'https://www.comcbt.com/xe/bk'},
  {'testName': '임업종묘기능사', 'url': 'https://www.comcbt.com/xe/caw'},
  {'testName': '임업종묘기사', 'url': 'https://www.comcbt.com/xe/ceq'},
  {'testName': '자기비파괴검사기능사', 'url': 'https://www.comcbt.com/xe/dm'},
  {'testName': '자기비파괴검사기사', 'url': 'https://www.comcbt.com/xe/ei'},
  {'testName': '자기비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/er'},
  {'testName': '자기비파괴검사산업기사', 'url': 'https://www.comcbt.com/xe/gn'},
  {'testName': '자기비파괴검사산업기사(구)', 'url': 'https://www.comcbt.com/xe/go'},
  {'testName': '자동차보수도장기능사', 'url': 'https://www.comcbt.com/xe/dn'},
  {'testName': '자동차정비기능사', 'url': 'https://www.comcbt.com/xe/jq'},
  {'testName': '자동차정비기능장', 'url': 'https://www.comcbt.com/xe/gm'},
  {'testName': '자동차정비기사', 'url': 'https://www.comcbt.com/xe/nt'},
  {'testName': '자동차정비산업기사', 'url': 'https://www.comcbt.com/xe/nn'},
  {'testName': '자동차차체수리기능사', 'url': 'https://www.comcbt.com/xe/ed'},
  {'testName': '자연생태복원기사', 'url': 'https://www.comcbt.com/xe/ceu'},
  {'testName': '자연생태복원기사(구)', 'url': 'https://www.comcbt.com/xe/eg'},
  {'testName': '자연생태복원산업기사', 'url': 'https://www.comcbt.com/xe/mu'},
  {'testName': '잠수기능사', 'url': 'https://www.comcbt.com/xe/f8'},
  {'testName': '잠수산업기사', 'url': 'https://www.comcbt.com/xe/mq'},
  {'testName': '잠수산업기사(구)', 'url': 'https://www.comcbt.com/xe/q8'},
  {'testName': '전기공사기사', 'url': 'https://www.comcbt.com/xe/ni'},
  {'testName': '전기공사산업기사', 'url': 'https://www.comcbt.com/xe/nr'},
  {'testName': '전기기능사', 'url': 'https://www.comcbt.com/xe/jo'},
  {'testName': '전기기능장', 'url': 'https://www.comcbt.com/xe/nu'},
  {'testName': '전기기사', 'url': 'https://www.comcbt.com/xe/kt'},
  {'testName': '전기산업기사', 'url': 'https://www.comcbt.com/xe/jw'},
  {'testName': '전기철도기사', 'url': 'https://www.comcbt.com/xe/my'},
  {'testName': '전기철도산업기사', 'url': 'https://www.comcbt.com/xe/nh'},
  {'testName': '전산세무 1급', 'url': 'https://www.comcbt.com/xe/h4'},
  {'testName': '전산세무 2급', 'url': 'https://www.comcbt.com/xe/h3'},
  {'testName': '전산응용건축제도기능사', 'url': 'https://www.comcbt.com/xe/jj'},
  {'testName': '전산응용기계제도기능사', 'url': 'https://www.comcbt.com/xe/jk'},
  {'testName': '전산응용조선제도기능사', 'url': 'https://www.comcbt.com/xe/cdh'},
  {'testName': '전산응용토목제도기능사', 'url': 'https://www.comcbt.com/xe/n2'},
  {'testName': '전산회계 1급', 'url': 'https://www.comcbt.com/xe/h1'},
  {'testName': '전산회계 2급', 'url': 'https://www.comcbt.com/xe/h2'},
  {'testName': '전산회계운용사 1급', 'url': 'https://www.comcbt.com/xe/g8'},
  {'testName': '전산회계운용사 2급', 'url': 'https://www.comcbt.com/xe/g9'},
  {'testName': '전산회계운용사 3급', 'url': 'https://www.comcbt.com/xe/ga'},
  {'testName': '전자계산기기능사', 'url': 'https://www.comcbt.com/xe/jz'},
  {'testName': '전자계산기기사', 'url': 'https://www.comcbt.com/xe/kx'},
  {'testName': '전자계산기제어산업기사', 'url': 'https://www.comcbt.com/xe/cep'},
  {'testName': '전자계산기제어산업기사(구)', 'url': 'https://www.comcbt.com/xe/ceo'},
  {'testName': '전자계산기조직응용기사', 'url': 'https://www.comcbt.com/xe/ji'},
  {'testName': '전자기기기능사', 'url': 'https://www.comcbt.com/xe/n6'},
  {'testName': '전자기기기능장', 'url': 'https://www.comcbt.com/xe/na'},
  {'testName': '전자기사', 'url': 'https://www.comcbt.com/xe/bf'},
  {'testName': '전자부품장착기능사', 'url': 'https://www.comcbt.com/xe/gd'},
  {'testName': '전자산업기사', 'url': 'https://www.comcbt.com/xe/ky'},
  {'testName': '전자상거래운용사', 'url': 'https://www.comcbt.com/xe/c4'},
  {'testName': '전자출판기능사', 'url': 'https://www.comcbt.com/xe/jp'},
  {'testName': '전자캐드기능사', 'url': 'https://www.comcbt.com/xe/n7'},
  {'testName': '전파전자기능사(구)', 'url': 'https://www.comcbt.com/xe/fv'},
  {'testName': '전파전자통신기능사', 'url': 'https://www.comcbt.com/xe/fw'},
  {'testName': '전파전자통신기사', 'url': 'https://www.comcbt.com/xe/rs'},
  {'testName': '전파통신기능사(구)', 'url': 'https://www.comcbt.com/xe/fx'},
  {'testName': '정밀측정기능사', 'url': 'https://www.comcbt.com/xe/ccd'},
  {'testName': '정밀측정산업기사', 'url': 'https://www.comcbt.com/xe/cm'},
  {'testName': '정보기기운용기능사', 'url': 'https://www.comcbt.com/xe/j2'},
  {'testName': '정보보안기사', 'url': 'https://www.comcbt.com/xe/ccw'},
  {'testName': '정보처리기능사', 'url': 'https://www.comcbt.com/xe/j1'},
  {'testName': '정보처리기능사 실기(베타)', 'url': 'https://www.comcbt.com/xe/jb'},
  {'testName': '정보처리기사', 'url': 'https://www.comcbt.com/xe/iz'},
  {'testName': '정보처리기사(구)', 'url': 'https://www.comcbt.com/xe/j4'},
  {'testName': '정보처리산업기사', 'url': 'https://www.comcbt.com/xe/j3'},
  {'testName': '정보통신기사', 'url': 'https://www.comcbt.com/xe/cey'},
  {'testName': '정보통신기사(구)', 'url': 'https://www.comcbt.com/xe/ns'},
  {'testName': '정보통신산업기사', 'url': 'https://www.comcbt.com/xe/fu'},
  {'testName': '제강기능사', 'url': 'https://www.comcbt.com/xe/cfd'},
  {'testName': '제강기능장', 'url': 'https://www.comcbt.com/xe/cah'},
  {'testName': '제과기능사', 'url': 'https://www.comcbt.com/xe/j7'},
  {'testName': '제과기능장', 'url': 'https://www.comcbt.com/xe/vm'},
  {'testName': '제빵기능사', 'url': 'https://www.comcbt.com/xe/j8'},
  {'testName': '제선기능사', 'url': 'https://www.comcbt.com/xe/e2'},
  {'testName': '제선기능장', 'url': 'https://www.comcbt.com/xe/cai'},
  {'testName': '제품디자인기사', 'url': 'https://www.comcbt.com/xe/cdj'},
  {'testName': '제품디자인산업기사', 'url': 'https://www.comcbt.com/xe/cct'},
  {'testName': '제품응용모델링기능사', 'url': 'https://www.comcbt.com/xe/ccb'},
  {'testName': '조경기능사', 'url': 'https://www.comcbt.com/xe/jx'},
  {'testName': '조경기사', 'url': 'https://www.comcbt.com/xe/b9'},
  {'testName': '조경산업기사', 'url': 'https://www.comcbt.com/xe/d7'},
  {'testName': '조리기능장', 'url': 'https://www.comcbt.com/xe/vj'},
  {'testName': '조리산업기사(공통)', 'url': 'https://www.comcbt.com/xe/gg'},
  {'testName': '조선기사', 'url': 'https://www.comcbt.com/xe/cch'},
  {'testName': '조선산업기사', 'url': 'https://www.comcbt.com/xe/ccx'},
  {'testName': '조주기능사', 'url': 'https://www.comcbt.com/xe/k6'},
  {'testName': '종자기능사', 'url': 'https://www.comcbt.com/xe/ek'},
  {'testName': '종자기사', 'url': 'https://www.comcbt.com/xe/d8'},
  {'testName': '종자산업기사', 'url': 'https://www.comcbt.com/xe/gz'},
  {'testName': '주조기능사', 'url': 'https://www.comcbt.com/xe/cck'},
  {'testName': '주조기능장', 'url': 'https://www.comcbt.com/xe/cao'},
  {'testName': '주조산업기사', 'url': 'https://www.comcbt.com/xe/cdk'},
  {'testName': '주택관리사보 1차', 'url': 'https://www.comcbt.com/xe/cc'},
  {'testName': '주택관리사보 2차', 'url': 'https://www.comcbt.com/xe/cd'},
  {'testName': '지게차운전기능사', 'url': 'https://www.comcbt.com/xe/jg'},
  {'testName': '지게차유사(롤러,기중기등)', 'url': 'https://www.comcbt.com/xe/nx'},
  {'testName': '지적기능사', 'url': 'https://www.comcbt.com/xe/fq'},
  {'testName': '지적기사', 'url': 'https://www.comcbt.com/xe/ea'},
  {'testName': '지적산업기사', 'url': 'https://www.comcbt.com/xe/e4'},
  {'testName': '직업상담사 1급', 'url': 'https://www.comcbt.com/xe/mh'},
  {'testName': '직업상담사 1급(구)', 'url': 'https://www.comcbt.com/xe/mi'},
  {'testName': '직업상담사 2급', 'url': 'https://www.comcbt.com/xe/n3'},
  {'testName': '직업상담사 2급(구)', 'url': 'https://www.comcbt.com/xe/n4'},
  {'testName': '천장크레인운전기능사', 'url': 'https://www.comcbt.com/xe/br'},
  {'testName': '철도신호기사', 'url': 'https://www.comcbt.com/xe/hd'},
  {'testName': '철도신호산업기사', 'url': 'https://www.comcbt.com/xe/mb'},
  {'testName': '철도운송산업기사', 'url': 'https://www.comcbt.com/xe/ccn'},
  {'testName': '철도차량기사', 'url': 'https://www.comcbt.com/xe/cdx'},
  {'testName': '철도차량정비기능사', 'url': 'https://www.comcbt.com/xe/cfi'},
  {'testName': '철도차량정비기능사(구)', 'url': 'https://www.comcbt.com/xe/cfh'},
  {'testName': '철도차량정비기능장', 'url': 'https://www.comcbt.com/xe/cam'},
  {'testName': '철도토목기능사', 'url': 'https://www.comcbt.com/xe/cdi'},
  {'testName': '철도토목산업기사', 'url': 'https://www.comcbt.com/xe/cdf'},
  {'testName': '청소년상담사 1급(1교시)', 'url': 'https://www.comcbt.com/xe/hs'},
  {'testName': '청소년상담사 1급(1교시)(구)', 'url': 'https://www.comcbt.com/xe/hy'},
  {'testName': '청소년상담사 1급(2교시)', 'url': 'https://www.comcbt.com/xe/ht'},
  {'testName': '청소년상담사 1급(2교시)(구)', 'url': 'https://www.comcbt.com/xe/hz'},
  {'testName': '청소년상담사 2급(1교시)', 'url': 'https://www.comcbt.com/xe/hu'},
  {'testName': '청소년상담사 2급(1교시)(구)', 'url': 'https://www.comcbt.com/xe/m1'},
  {'testName': '청소년상담사 2급(2교시)', 'url': 'https://www.comcbt.com/xe/hv'},
  {'testName': '청소년상담사 2급(2교시)(구)', 'url': 'https://www.comcbt.com/xe/m2'},
  {'testName': '청소년상담사 3급(1교시)', 'url': 'https://www.comcbt.com/xe/hw'},
  {'testName': '청소년상담사 3급(1교시)(구)', 'url': 'https://www.comcbt.com/xe/m3'},
  {'testName': '청소년상담사 3급(2교시)', 'url': 'https://www.comcbt.com/xe/hx'},
  {'testName': '청소년상담사 3급(2교시)(구)', 'url': 'https://www.comcbt.com/xe/m4'},
  {'testName': '초음파비파괴검사기능사', 'url': 'https://www.comcbt.com/xe/dw'},
  {'testName': '초음파비파괴검사기사', 'url': 'https://www.comcbt.com/xe/ej'},
  {'testName': '초음파비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/es'},
  {'testName': '초음파비파괴검사산업기사', 'url': 'https://www.comcbt.com/xe/gv'},
  {'testName': '초음파비파괴검사산업기사(구)', 'url': 'https://www.comcbt.com/xe/gy'},
  {'testName': '축로기능사', 'url': 'https://www.comcbt.com/xe/ms'},
  {'testName': '축산기능사', 'url': 'https://www.comcbt.com/xe/gk'},
  {'testName': '축산기사', 'url': 'https://www.comcbt.com/xe/e9'},
  {'testName': '축산산업기사', 'url': 'https://www.comcbt.com/xe/fk'},
  {'testName': '측량기능사', 'url': 'https://www.comcbt.com/xe/dk'},
  {'testName': '측량및지형공간정보기사', 'url': 'https://www.comcbt.com/xe/dv'},
  {'testName': '측량및지형공간정보산업기사', 'url': 'https://www.comcbt.com/xe/ex'},
  {'testName': '치공구설계산업기사', 'url': 'https://www.comcbt.com/xe/ccq'},
  {'testName': '침투비파괴검사기능사', 'url': 'https://www.comcbt.com/xe/bq'},
  {'testName': '침투비파괴검사기사', 'url': 'https://www.comcbt.com/xe/e5'},
  {'testName': '침투비파괴검사기사(구)', 'url': 'https://www.comcbt.com/xe/ef'},
  {'testName': '침투비파괴검사산업기사', 'url': 'https://www.comcbt.com/xe/fg'},
  {'testName': '침투비파괴검사산업기사(구)', 'url': 'https://www.comcbt.com/xe/fh'},
  {'testName': '컨벤션기획사 2급', 'url': 'https://www.comcbt.com/xe/cex'},
  {'testName': '컨벤션기획사 2급(구)', 'url': 'https://www.comcbt.com/xe/ev'},
  {'testName': '컨테이너크레인운전기능사', 'url': 'https://www.comcbt.com/xe/gu'},
  {'testName': '컬러리스트기사', 'url': 'https://www.comcbt.com/xe/dh'},
  {'testName': '컬러리스트산업기사', 'url': 'https://www.comcbt.com/xe/bu'},
  {'testName': '컴퓨터그래픽스운용기능사', 'url': 'https://www.comcbt.com/xe/j5'},
  {'testName': '컴퓨터응용가공산업기사', 'url': 'https://www.comcbt.com/xe/bo'},
  {'testName': '컴퓨터응용밀링기능사', 'url': 'https://www.comcbt.com/xe/ju'},
  {'testName': '컴퓨터응용선반기능사', 'url': 'https://www.comcbt.com/xe/jt'},
  {'testName': '컴퓨터활용능력 1급', 'url': 'https://www.comcbt.com/xe/c1'},
  {'testName': '컴퓨터활용능력 2급', 'url': 'https://www.comcbt.com/xe/c2'},
  {'testName': '컴퓨터활용능력 3급(폐지)', 'url': 'https://www.comcbt.com/xe/c3'},
  {'testName': '콘크리트기능사', 'url': 'https://www.comcbt.com/xe/dr'},
  {'testName': '콘크리트기사', 'url': 'https://www.comcbt.com/xe/e1'},
  {'testName': '콘크리트산업기사', 'url': 'https://www.comcbt.com/xe/gj'},
  {'testName': '타워크레인운전기능사', 'url': 'https://www.comcbt.com/xe/fy'},
  {'testName': '텔레마케팅관리사', 'url': 'https://www.comcbt.com/xe/k8'},
  {'testName': '토목기사', 'url': 'https://www.comcbt.com/xe/n1'},
  {'testName': '토목산업기사', 'url': 'https://www.comcbt.com/xe/e3'},
  {'testName': '토양환경기사', 'url': 'https://www.comcbt.com/xe/eh'},
  {'testName': '통신기기기능사', 'url': 'https://www.comcbt.com/xe/cac'},
  {'testName': '통신선로기능사', 'url': 'https://www.comcbt.com/xe/cad'},
  {'testName': '통신선로산업기사', 'url': 'https://www.comcbt.com/xe/ces'},
  {'testName': '통신설비기능장', 'url': 'https://www.comcbt.com/xe/nb'},
  {'testName': '특수용접기능사', 'url': 'https://www.comcbt.com/xe/js'},
  {'testName': '판금제관기능장', 'url': 'https://www.comcbt.com/xe/cas'},
  {'testName': '판금제관산업기사', 'url': 'https://www.comcbt.com/xe/ceb'},
  {'testName': '패션디자인산업기사', 'url': 'https://www.comcbt.com/xe/c8'},
  {'testName': '패션머천다이징산업기사', 'url': 'https://www.comcbt.com/xe/c7'},
  {'testName': '폐기물처리기사', 'url': 'https://www.comcbt.com/xe/dj'},
  {'testName': '폐기물처리산업기사', 'url': 'https://www.comcbt.com/xe/fc'},
  {'testName': '포장기사', 'url': 'https://www.comcbt.com/xe/cdp'},
  {'testName': '포장산업기사', 'url': 'https://www.comcbt.com/xe/cdv'},
  {'testName': '표면처리기능사', 'url': 'https://www.comcbt.com/xe/q1'},
  {'testName': '표면처리기능장', 'url': 'https://www.comcbt.com/xe/car'},
  {'testName': '표면처리산업기사', 'url': 'https://www.comcbt.com/xe/caz'},
  {'testName': '품질경영기사', 'url': 'https://www.comcbt.com/xe/bp'},
  {'testName': '품질경영산업기사', 'url': 'https://www.comcbt.com/xe/ep'},
  {'testName': '플라스틱창호기능사', 'url': 'https://www.comcbt.com/xe/dx'},
  {'testName': '피아노조율기능사', 'url': 'https://www.comcbt.com/xe/ccg'},
  {'testName': '피아노조율산업기사', 'url': 'https://www.comcbt.com/xe/cdd'},
  {'testName': '한국사능력검정시험 기본', 'url': 'https://www.comcbt.com/xe/mc'},
  {'testName': '한국사능력검정시험 심화', 'url': 'https://www.comcbt.com/xe/k1'},
  {'testName': '한국사능력검정시험 중급(폐지)', 'url': 'https://www.comcbt.com/xe/k2'},
  {'testName': '한국사능력검정시험 초급(폐지)', 'url': 'https://www.comcbt.com/xe/k3'},
  {'testName': '한국수어교원자격검정', 'url': 'https://www.comcbt.com/xe/eu'},
  {'testName': '한복기능사', 'url': 'https://www.comcbt.com/xe/m5'},
  {'testName': '한복산업기사', 'url': 'https://www.comcbt.com/xe/cay'},
  {'testName': '한식조리기능사', 'url': 'https://www.comcbt.com/xe/ja'},
  {'testName': '항공기관정비기능사', 'url': 'https://www.comcbt.com/xe/bs'},
  {'testName': '항공기사', 'url': 'https://www.comcbt.com/xe/ccy'},
  {'testName': '항공기체정비기능사', 'url': 'https://www.comcbt.com/xe/kw'},
  {'testName': '항공무선통신사', 'url': 'https://www.comcbt.com/xe/hr'},
  {'testName': '항공산업기사', 'url': 'https://www.comcbt.com/xe/b7'},
  {'testName': '항공장비정비기능사', 'url': 'https://www.comcbt.com/xe/f9'},
  {'testName': '항공전자정비기능사', 'url': 'https://www.comcbt.com/xe/cab'},
  {'testName': '항로표지기능사', 'url': 'https://www.comcbt.com/xe/ccc'},
  {'testName': '항로표지기사', 'url': 'https://www.comcbt.com/xe/vo'},
  {'testName': '항로표지산업기사', 'url': 'https://www.comcbt.com/xe/ccz'},
  {'testName': '해상무선통신사', 'url': 'https://www.comcbt.com/xe/cft'},
  {'testName': '해양공학기사', 'url': 'https://www.comcbt.com/xe/cdr'},
  {'testName': '해양자원개발기사', 'url': 'https://www.comcbt.com/xe/cdq'},
  {'testName': '해양조사산업기사', 'url': 'https://www.comcbt.com/xe/mp'},
  {'testName': '해양환경기사', 'url': 'https://www.comcbt.com/xe/mg'},
  {'testName': '화공기사', 'url': 'https://www.comcbt.com/xe/cev'},
  {'testName': '화공기사(구)', 'url': 'https://www.comcbt.com/xe/bi'},
  {'testName': '화공기사(구)(구)', 'url': 'https://www.comcbt.com/xe/bm'},
  {'testName': '화약류관리기사', 'url': 'https://www.comcbt.com/xe/ca'},
  {'testName': '화약류관리산업기사', 'url': 'https://www.comcbt.com/xe/mt'},
  {'testName': '화약취급기능사', 'url': 'https://www.comcbt.com/xe/q3'},
  {'testName': '화재감식평가기사', 'url': 'https://www.comcbt.com/xe/ew'},
  {'testName': '화재감식평가산업기사', 'url': 'https://www.comcbt.com/xe/fj'},
  {'testName': '화학분석기능사', 'url': 'https://www.comcbt.com/xe/eo'},
  {'testName': '화학분석기사', 'url': 'https://www.comcbt.com/xe/ry'},
  {'testName': '화학분석기사(구)', 'url': 'https://www.comcbt.com/xe/d5'},
  {'testName': '화훼장식기능사', 'url': 'https://www.comcbt.com/xe/ko'},
  {'testName': '화훼장식기사', 'url': 'https://www.comcbt.com/xe/m8'},
  {'testName': '환경기능사', 'url': 'https://www.comcbt.com/xe/kr'},
  {'testName': '화훼장식기능사', 'url': 'https://www.comcbt.com/xe/ko'},
  {'testName': '화훼장식기사', 'url': 'https://www.comcbt.com/xe/m8'},
  {'testName': '환경기능사', 'url': 'https://www.comcbt.com/xe/kr'},
];
